version: '3.8'
services:
  osrm:
    image: osrm/osrm-backend
    volumes:
      - ./data:/data
    ports:
      - "5000:5000"
    command: /bin/bash -c "\
      osrm-routed --algorithm mld /data/niedersachsen-latest.osrm"


      

