version: '3.8'
services:
  osrm:
    image: osrm/osrm-backend
    volumes:
      - ./data:/data
    ports:
      - "5000:5000"
    command: /bin/bash -c "\
      osrm-extract -p /opt/foot.lua /data/niedersachsen-latest.osm.pbf && \
      osrm-partition /data/niedersachsen-latest.osrm && \
      osrm-customize /data/niedersachsen-latest.osrm && \
      osrm-routed --algorithm mld /data/niedersachsen-latest.osrm"
  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "80:80"


      

