version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: meineDatenbank
      POSTGRES_USER: meinBenutzer
      POSTGRES_PASSWORD: meinPasswort
    ports:
      - "5432:5432"

volumes:
  postgres-data:
